version: "3.6"

services:
  # ===== React DEV =====
  express-dev:
    container_name: Express.js-DEVELOPMENT-container
    build:
      context: "./server"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - ./server:/server
    environment:
      DB_NAME: ${DEV_DB_NAME}


  react-dev:
    container_name: React.js-DEVELOPMENT-container
    build:
      context: "./client"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    healthcheck:
      test: ["CMD", "wget -qO- localhost:8000/"]
      interval: 10s
      timeout: 5s
      start_period: 60s