version: '3.6'

services:


  # ===== DEV =====
  express-dev:
    container_name: Express.js-DEVELOPMENT-container
    build:
      context: .
      target: DEV
    restart: always
    tty: true
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes: # For debugging purposes
      - ./src:/code/src
      - ./public:/code/public   
    environment:
      # DB credentials needed to connect to the db
      DB_NAME: ${DEV_DB_NAME}
      # DEBUG: true


  # ==== PROD =====
  express-prod:
    container_name: Express.js-PRODUCTION-container
    build:
      context: .
      target: PROD
    restart: always
    tty: true
    ports:
      - "3000:3000"
    environment:
      # DB credentials needed to connect to the db
      DB_NAME: ${PROD_DB_NAME}